version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'app'
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npm start"
    user: "1000:1000"

networks:
  default:
    name: local
