apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: memarchi/production-microservice:latest
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: RECEIVE_MESSAGE_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: receive-message-queue
            - name: SEND_MESSAGE_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: send-message-queue
            - name: TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: table-name
            
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  receive-message-queue: https://sqs.us-east-1.amazonaws.com/471112746092/approved_payment.fifo
  send-message-queue: https://sqs.us-east-1.amazonaws.com/471112746092/update_order.fifo
  table-name: production
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
  type: LoadBalancer
