apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: devrsilva/production-microsservice
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/livenessProbe
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/readinessProbe
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          env:
            - name: RECEIVE_MESSAGE_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: receive-message-queue
            - name: SEND_MESSAGE_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: send-message-queue
            - name: TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: table-name
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: aws-region
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: AWS_SECRET_KEY

            
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
stringData:
  receive-message-queue: https://sqs.us-east-1.amazonaws.com/471112746092/approved_payment.fifo
  send-message-queue: https://sqs.us-east-1.amazonaws.com/471112746092/update_order.fifo
  table-name: production
  aws-region: us-east-1
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003
  type: LoadBalancer
