apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-production-deployment
spec:
  selector:
    matchLabels:
      app: api-production
  template:
    metadata:
      labels:
        app: api-production
    spec:
      containers:
        - name: api-production-deployment
          image: devrsilva/production-microsservice
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3003
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/v1/livenessProbe
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/v1/readinessProbe
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 10
          env:
            - name: APPROVED_PAYMENT_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-production-secrets
                  key: approved-payment-queue
            - name: UPDATE_ORDER_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-production-secrets
                  key: update-order-queue
            - name: CANCEL_ORDER_QUEUE
              valueFrom:
                secretKeyRef:
                  name: api-production-secrets
                  key: cancel-order-queue
            - name: TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: api-production-secrets
                  key: table-name
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: api-production-secrets
                  key: aws-region
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: api-production-secrets
                  key: port
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: production-credentials
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: production-credentials
                  key: AWS_SECRET_KEY

            
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-production-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-production-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
apiVersion: v1
kind: Secret
metadata:
  name: api-production-secrets
type: Opaque
stringData:
  approved-payment-queue: https://sqs.us-east-1.amazonaws.com/471112746092/approved_payment.fifo
  update-order-queue: https://sqs.us-east-1.amazonaws.com/471112746092/update_order.fifo
  cancel-order-queue: https://sqs.us-east-1.amazonaws.com/471112746092/cancel_order.fifo
  table-name: production
  aws-region: us-east-1
  port: '3003'
---
apiVersion: v1
kind: Service
metadata:
  name: api-production-svc
spec:
  selector:
    app: api-production
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003
  type: LoadBalancer
